CC= arm-none-eabi-
CFLAGS=-mcpu=arm926ej-s -g
INCS=-I .
LIRS=
SRC=$(wildcard *.c)
OBJ=$(SRC:.c=.o)
AS=$(wildcard *.s)
ASOBJ=$(AS:.s=.o)
FILE_NAME=learn_in_depth
all: learn_in_depth.bin
	@echo "Done "

%.o: %.s
	$(CC)as.exe $(CFLAGS) $< -o $@
%.o: %.c
	 $(CC)gcc.exe -c $(FLAGS) $(INCS) $< -o $@
$(FILE_NAME).elf: $(OBJ) $(ASOBJ)
	 $(CC)ld.exe -T  linker_script.ld -Map=output.map $(OBJ) $(ASOBJ) -o $(FILE_NAME).elf

$(FILE_NAME).bin: $(FILE_NAME).elf
	$(CC)objcopy.exe -O binary $< $@ 
clean:
	rm -rf *.o *.bin *.elf
	@echo "Everything Clean"      





	
	
              

 
