/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef volatile unsigned int vuint32_t;
#include <stdint.h>
#define RCC_BASE 0x40021000
#define RCC_IOPAEN (1<<2)
#define RCC_APB2ENR *(vuint32_t*)(RCC_BASE+0x18)


//port A
#define GPIOA_BASE 0x40010800
#define GPIOA_CRH *(vuint32_t*)(GPIOA_BASE+0x04)
#define GPIOA_CRL *(vuint32_t*)(GPIOA_BASE+0x00)
#define GPIOA_ODR *(vuint32_t*)(GPIOA_BASE+0x0c)
#define GPIOA_IDR *(vuint32_t*)(GPIOA_BASE+0x08)
//port B
#define GPIOB_BASE 0x40010C00
#define GPIOB_CRH *(vuint32_t*)(GPIOB_BASE+0x04)
#define GPIOB_CRL *(vuint32_t*)(GPIOB_BASE+0x00)
#define GPIOB_ODR *(vuint32_t*)(GPIOB_BASE+0x0c)
#define GPIOB_IDR *(vuint32_t*)(GPIOB_BASE+0x08)

 void init_GPIO()
 {



 GPIOA_CRL=0;
 GPIOA_CRH=0;
 GPIOA_ODR=0;


	//A1 input floating 01
 GPIOA_CRL&=~(0b11<<4);
	GPIOA_CRL|=(0b01<<6);
 //B1 output push pull
		GPIOB_CRL|=(0b01<<4);
		GPIOB_CRL&=~(0b11<<6);

	// A13 input floating
	 GPIOA_CRH&=~(0b11<<20);
		GPIOA_CRH|=(0b01<<22);


	//b13 output push pull
		GPIOB_CRH|=(0b01<<20);
		GPIOB_CRH&=~(0b11<<22);

 }
 void init_clock()
 {
	 //GPIO enable clock
	 RCC_APB2ENR |=RCC_IOPAEN;
	 RCC_APB2ENR |=(1<<3);
 }
 void dely(int x)
 {
	 unsigned int i,j;
	 for (i=0;i<x;i++)
		 for (j=0;j<255;j++);
 }
int main(void)
{
	init_clock();
	init_GPIO();
	volatile char flag =1;
	while (1){

		if (!(GPIOA_IDR&(1<<1)))
		{
			if (flag)
			GPIOB_ODR^=(1<<1);
			flag=0;

		}
		else flag=1;
		if ((GPIOA_IDR&(1<<13)))
		{
			GPIOB_ODR^=(1<<13);


		}

		dely(10);

	}
}

