/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include "STM32f103C6_GPIO_DRIVER.h"
#include "STM32f103x6.h"
#include "lcd.h"
#include "keypad.h"
#include "STM32f103C6_EXTI_DRIVER.h"

// Number from 1 to 9 in Hexadecimal For a common anode seven-segment display
#define Zero   0xC0  // 0b11000000
#define One    0xF9  // 0b11111001
#define Two    0xA4  // 0b10100100
#define Three  0xB0  // 0b10110000
#define Four   0x99  // 0b10011001
#define Five   0x92  // 0b10010010
#define Six    0x82  // 0b10000010
#define Seven  0xF8  // 0b11111000
#define Eight  0x80  // 0b10000000
#define Nine   0x90  // 0b10010000


void init_GPIO()
{





	PinConfig.GPIO_MODE=GPIO_MODE_Output_PP;
	PinConfig.GPIO_PinNumber=GPIO_PIN_9;
	PinConfig.GPIO_Output_Speed=GPIO_SPEED_10MHz;
	MCAL_GPIO_Init(GPIOB,&PinConfig);

	PinConfig.GPIO_MODE=GPIO_MODE_Output_PP;
	PinConfig.GPIO_PinNumber=GPIO_PIN_10;
	PinConfig.GPIO_Output_Speed=GPIO_SPEED_10MHz;
	MCAL_GPIO_Init(GPIOB,&PinConfig);

	PinConfig.GPIO_MODE=GPIO_MODE_Output_PP;
	PinConfig.GPIO_PinNumber=GPIO_PIN_11;
	PinConfig.GPIO_Output_Speed=GPIO_SPEED_10MHz;
	MCAL_GPIO_Init(GPIOB,&PinConfig);

	PinConfig.GPIO_MODE=GPIO_MODE_Output_PP;
	PinConfig.GPIO_PinNumber=GPIO_PIN_12;
	PinConfig.GPIO_Output_Speed=GPIO_SPEED_10MHz;
	MCAL_GPIO_Init(GPIOB,&PinConfig);

	PinConfig.GPIO_MODE=GPIO_MODE_Output_PP;
	PinConfig.GPIO_PinNumber=GPIO_PIN_13;
	PinConfig.GPIO_Output_Speed=GPIO_SPEED_10MHz;
	MCAL_GPIO_Init(GPIOB,&PinConfig);

	PinConfig.GPIO_MODE=GPIO_MODE_Output_PP;
	PinConfig.GPIO_PinNumber=GPIO_PIN_14;
	PinConfig.GPIO_Output_Speed=GPIO_SPEED_10MHz;
	MCAL_GPIO_Init(GPIOB,&PinConfig);

	PinConfig.GPIO_MODE=GPIO_MODE_Output_PP;
	PinConfig.GPIO_PinNumber=GPIO_PIN_15;
	PinConfig.GPIO_Output_Speed=GPIO_SPEED_10MHz;
	MCAL_GPIO_Init(GPIOB,&PinConfig);



}
uint8_t Flag=1;
void init_clock()
{
	//GPIO enable clock
	RCC_GPIOA_CLK_ENABLE();
	RCC_GPIOB_CLK_ENABLE();
	RCC_AFIO_CLK_ENABLE();
}
void ISR_EXTI9(void){

	LCD_WRITE_STRING("Interrupt is happening _|-");
	delay(100);
}
int main(void)
{
	init_clock();
	//	init_GPIO();
	LCD_INIT();
	LCD_clear_screen();
	EXTI_PinConfig_t myEXTI;
	myEXTI.EXTI_PIN = EXTI9PB9;
	myEXTI.Trigger_CASE = EXTI_TRIGGER_RISING;
	myEXTI.IRQ_EN = EXTI_IRQ_ENABLE;
	myEXTI.P_IRQ_CALLBACK_FUN = ISR_EXTI9;
	MCAL_EXTI_GPIO_Init(&myEXTI);
	while (1){
		if (Flag==0)
		{
			LCD_clear_screen();
			delay(100);
		}
	}
}

